MPIVER=
CMAKETYPE=Release
PETSC_DIR=/home/jchen/LIB/petsc-3.19.5
PETSC_ARCH=kairos-intel-craympich-cplx
PARMETIS_INSTALL_DIR=$PETSC_DIR/$PETSC_ARCH
#SCOREC_DIR=$HOME/LIB/core-trunk/KAIROS
SCOREC_DIR=/opt/nfri/lib/m3dc1/LIB/core-trunk/KAIROS
PREFIX=$SCOREC_DIR
#add -DPETSCMASTER for petsc 3.8.3 or higher

#cmake .. \
$PETSC_DIR/$PETSC_ARCH/bin/cmake ..\
  -DCMAKE_C_COMPILER="cc" \
  -DCMAKE_CXX_COMPILER="CC" \
  -DCMAKE_Fortran_COMPILER="ftn" \
  -DCMAKE_C_FLAGS=" -g -fPIC -O0 -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS=" -g -fPIC -O0 -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fPIC "\
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$SCOREC_DIR/include" \
  -DSCOREC_LIB_DIR="$SCOREC_DIR/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=ON \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE \

