#!/bin/bash

if [ -z "$1" ]; then
    suffix="${M3DC1_ARCH}"
else
    suffix="$1"
fi

if [ -z "${suffix}" ]; then
    suffix="test"
fi

if [ -z "${M3DC1_VERSION}" ]; then
    M3DC1_VERSION="local"
fi

echo "Suffix = $suffix"
echo "M3DC1_VERSION = $M3DC1_VERSION"

wd=`pwd`

# Name of the test directory
test="${M3DC1_VERSION}_${suffix}"

for d in */ ; do
    if [ -d "${wd}/${d}${test}" ]; then
        rm -fr "${wd}/${d}${test}"
    fi
done